Repository aesara-devs/aemcmc, pull requests merged in 2023-02, with the labels that each got.

#97 Update pre-commit versions
  .pre-commit-config.yaml
Labels: CI, bug

#98 Update the README
  README.md
  README.rst
Labels: documentation

#100 Add Gitter badge and links to README
  README.md
Labels: documentation

#105 Add negative-binomial conjugate rewrite
  aemcmc/conjugates.py
  tests/test_basic.py
  tests/test_conjugates.py
Labels: enhancement, exact posterior

#110 Updates for new Aesara deprecations and AePPL version
  aemcmc/transforms.py
  environment.yml
  setup.py
  tests/test_basic.py
  tests/test_conjugates.py
  tests/test_rewriting.py
Labels: important, refactoring
